# Generated by Django 3.2.23 on 2024-01-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('IN', 'Check-In'), ('OUT', 'Check-Out')], max_length=4)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
